name: simoric
description: Measure PPG using the phone's camera.

version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  camera:
    git:
      url: https://github.com/Renesanse/plugins.git
      path: packages/camera/camera
      
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_database: ^4.1.1
  flutter_svg: ^0.19.0
  flutter_swiper: ^1.1.6
  http: null
  path_provider: ^1.6.18
  responsive_framework: ^0.0.8
  rxdart: ^0.24.1
  shared_preferences: null
  sqflite: ^1.3.1+1
  stacked_services: ^0.5.4+4
  wakelock: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emojis/
    - assets/iconos/
    - assets/images/
    - assets/swiper/
